### ISSUE TITLE
Error after importing in Android Studio 1.5.1

### ISSUE THREAD

**Issue by robertmathew** [LouisCAD/GoogleDevelopersColorScheme#1]
![screenshot from 2016-01-30 09-35-54](https://cloud.githubusercontent.com/assets/2344947/12693641/bab34130-c735-11e5-911e-21007e3c4b51.jpg)

**Comment by SiddharthPant** [comment]
Yup this happens for me too on latest AS 1.5.1(Windows 10). Due to this its not showing the colorscheme in the option.

**Comment by S4ntiagoHR** [comment]
me too, "unsupported color scheme version: 142", i have AS 1.5.1.

**Comment by LouisCAD** [comment]
Fixed in v1.0.1! Thanks for reporting
