### ISSUE TITLE
Cannot read scheme Google Developers.icls  

### ISSUE THREAD

**Issue by mkaarthick** [LouisCAD/GoogleDevelopersColorScheme#3]
Hi, after importing and restarting Android Studio, I'm getting this error..

`Cannot read scheme Google Developers.icls  from '$ROOT_CONFIG$/colors': Argument for @NotNull parameter 'element' of com/intellij/openapi/editor/markup/TextAttributes.<init> must not be null`

**Comment by LouisCAD** [comment]
Hi @mkaarthick,
Which Android Studio version are you running?

Can you attach a screenshot of the error to give me a hint about it's source, please?

**Comment by mkaarthick** [comment]
![capture](https://cloud.githubusercontent.com/assets/1816153/13107284/e97495bc-d592-11e5-82f7-2130432cc60d.PNG)

I'm using Android Studio AI-141.2024585

**Comment by LouisCAD** [comment]
It's not this version number I need to know. Is it 1.5.1? 2.0beta5?

**Comment by mkaarthick** [comment]
Old 1.3 Beta 1 EAP.0

**Comment by LouisCAD** [comment]
@mkaarthick So update Android Studio to 1.5.1 stable version or to canary or beta channel latest version

**Comment by LouisCAD** [comment]
I added info about compatibility in the readme.Consider seriously having up to date dev tools
