### ISSUE TITLE
Import package name fonts different

### ISSUE THREAD

**Issue by robertmathew** [LouisCAD/GoogleDevelopersColorScheme#4]
Why package names fonts are different? Some are plain text, bold or italic. Is it on purpose?

![screenshot from 2016-02-17 16-55-39](https://cloud.githubusercontent.com/assets/2344947/13108406/bc66e268-d598-11e5-942f-19ec36715e9e.png)

**Comment by LouisCAD** [comment]
Bold ones are non abstract classes while italic non bold ones are interfaces or abstract classes

**Comment by robertmathew** [comment]
Great. That's helpful. :thumbsup:
