### ISSUE TITLE
Show in Dark style Gradle files and Reg Expr

### ISSUE THREAD

**Issue by webserveis** [LouisCAD/GoogleDevelopersColorScheme#6]
In colors Graddle file and Reg Expresions show in Dark style theme

I Use the last Android Studio 2.1 version

**Comment by LouisCAD** [comment]
@webserveis Can you attach screenshots please?

**Comment by webserveis** [comment]
@LouisCAD solved in Colors & Fonts - General - Injected language fragment remove black background
